name: FastAPI continuous deployment workflow.

on:
  push:
    # branches:
    #   - main 
    paths:
      - 'api/**'
      - '.github/workflows/api_continuous_deployment.yaml'
      - '.github/workflows/api_deployment.yaml'

jobs:
  health-check-job:
    uses: ./.github/workflows/api_continuous_integration.yaml
    secrets: inherit  # The secrets used in the repository are inherited and made available to this job.

  build-and-deploy:
    needs: [health-check-job]   # It will only start if the health-check-job completes without errors.
    uses: ./.github/workflows/api_deployment.yaml
    with:
        app_name: apimodeletemplate   #  It passes the app_name input to the api_deployment.yaml workflow, setting the value to apimodeletemplate.
    secrets: inherit

