name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
      - test-ci-workflow
      
    paths:
        - 'api/**'
        - '.github/workflows/api_continuous_integration.yaml'
  pull_request:
      types: [opened, synchronize, reopened]
      branches:
          - main
          - develop
      paths:
        - 'api/**'
        - '.github/workflows/api_continuous_integration.yaml'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.9' 

      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version

      - name: Install dependencies
        run: |
          # python -m venv myenv
          # . myenv/bin/activate

          pip install -r requirements.txt

      - name: Set PYTHONPATH environment variable
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          # . myenv/bin/activate
          pytest
