name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
      - test-ci-workflow
  pull_request:
          types: [opened, synchronize, reopened]
          branches:
              - main
              - develop
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source myenv/bin/activate
          PYTHONPATH=./ pytest api/tests/
